### ISSUE TITLE
Use better fonts

### ISSUE THREAD

**Issue by nazarov-tech** [spbpython/kdpv_generator#2]
requirements:

- should be 4 .ttf files: regular, bold, italic, italic bold
- should be allowed for us to use (by license)
- should support cyrillic

**Comment by teners** [comment]
What could be better than old good [Bebas Neue](http://www.fontfabric.com/bebas-neue/)?

![Bebas Neue font cyrillic preview](http://www.fontfabric.com//wp-content/themes/unstandard/images/bebas05.gif)

![Bebas Neue font weights preview](http://www.fontfabric.com//wp-content/themes/unstandard/images/bebas02.gif)

**Comment by nazarov-tech** [comment]
done
