### ISSUE TITLE
Add multiple talks support

### ISSUE THREAD

**Issue by nazarov-tech** [spbpython/kdpv_generator#6]

**Comment by delimitry** [comment]
Multiple talks => multiple KDPV images?

**Comment by nazarov-tech** [comment]
@delimitry no, one KDPV image. I'm talking about multiple photo-talk-speaker rows (currently there's one row). "SPb Python" and the logo should displayed only once though.

**Comment by karech** [comment]
Now you can just increase image height and add new elements to image config.

**Comment by nazarov-tech** [comment]
priority increased

**Comment by nazarov-tech** [comment]
Need to implement config and put it into `configs/` dir.

**Comment by nazarov-tech** [comment]
this is the example: https://pbs.twimg.com/media/C-4xeF5XoAA8emS.jpg

**Comment by nazarov-tech** [comment]
done in https://github.com/spbpython/kdpv_generator/commit/d55dd561f172c29b6d658943ac690b4ee2bca407
